### PR TITLE
WIP - Update to 1.4 changes

### PR DESCRIPTION
**Pull request by BenDol**
A lot of these I am trying to learn on the fly so might be wrong, feel free to pull this and finish it or comment on parts that need fixing here.

Roughly 60~ files left to update still.

### CODE REVIEW

**Comment by slugmandrew** [comment]
Lol, I was just logging in to spend the day on this! Apologies to Mark and everyone else for not having more time to spend on this recently. Life has been hectic having just moved home.

Anyway, I'll merge this in and see what else I can add.

**Comment by slugmandrew** [comment]
OK, as this is WIP and I seem to have been left behind a bit I'll leave it to @BenDol to finish. I'm happy to help but I'm not really sure what's going on anymore!

`<inherits name="gwt.material.design.GwtMaterialWithJQuery"/>` Are you including JQuery in the project now @kevzlou7979 ?

**Comment by BenDol** [comment]
Materialize.js requires JQuery I believe.

**Comment by BenDol** [comment]
The new modules are defined in my PR here https://github.com/GwtMaterialDesign/gwt-material/pull/113

**Pull request merged**
